# Generated by Django 4.2.29 on 2026-04-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0002_pcbuild_description_pcbuild_image_url_pcbuild_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcbuild',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pcbuild',
            name='is_prebuilt',
            field=models.BooleanField(default=True),
        ),
    ]
