# Generated by Django 4.2.29 on 2026-04-14 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PCBuild',
            fields=[
                ('build_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='My Custom Build', max_length=255)),
                ('components', models.JSONField(default=list, help_text='List of component names/details selected in the builder.')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pc_builds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
