# Generated by Django 4.2 on 2026-03-31 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0006_productreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PCBuild',
            fields=[
                ('build_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PCBuildItem',
            fields=[
                ('build_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('component_type', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='builds.pcbuild')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_items', to='products.productvariant')),
            ],
            options={
                'unique_together': {('build', 'variant')},
            },
        ),
    ]
