# Generated by Django 4.2 on 2026-04-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcbuild',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pcbuild',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='prebuilt_pcs/'),
        ),
        migrations.AddField(
            model_name='pcbuild',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
