# Generated by Django 4.2.29 on 2026-04-14 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_cooler_cooler_type_alter_cooler_height_mm_and_more'),
        ('core', '0001_initial'),
        ('orders', '0004_alter_cartitem_unique_together_cartitem_build_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='build',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='order_items', to='core.pcbuild'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='build',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='core.pcbuild'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='order_items', to='products.productvariant'),
        ),
    ]
