# Generated by Django 4.2 on 2026-04-05 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_add_payment_method'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CashfreeOrder',
        ),
    ]
