# Generated by Django 4.2 on 2026-03-29 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_initial'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='Brand',
        # ),
        # migrations.DeleteModel(
        #     name='Category',
        # ),
    ]
