# Generated by Django 4.2 on 2026-04-12 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_product_is_trending"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cooler",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tdp", models.PositiveIntegerField(blank=True, help_text="In Watts", null=True)),
                ("cooler_type", models.CharField(choices=[("AIR", "Air Cooler"), ("AIO", "AIO Liquid Cooler")], max_length=10)),
                ("supported_sockets", models.JSONField(blank=True, default=list)),
                ("height_mm", models.PositiveIntegerField()),
                ("radiator_size_mm", models.PositiveIntegerField(blank=True, null=True)),
                ("variant", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s_specs", to="products.productvariant")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
