# Generated by Django 4.2 on 2026-04-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_cf_order_id_order_cf_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('card', 'Credit/Debit Card'), ('upi', 'UPI'), ('wallet', 'Wallet'), ('netbanking', 'Net Banking'), ('cardless_emi', 'Cardless EMI'), ('paypal', 'PayPal'), ('cod', 'Cash on Delivery')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Credit/Debit Card'), ('upi', 'UPI'), ('wallet', 'Wallet'), ('netbanking', 'Net Banking'), ('cardless_emi', 'Cardless EMI'), ('paypal', 'PayPal'), ('cod', 'Cash on Delivery')], max_length=20),
        ),
    ]
