# Generated by Django 4.2 on 2026-04-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cf_order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cf_payment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_raw',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_session_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_session_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.CharField(default='cashfree', max_length=50),
        ),
    ]
