# Generated by Django 4.2 on 2026-04-05 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_move_cf_fields_to_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_session_id',
        ),
    ]
