# Generated by Django 4.2 on 2026-04-05 17:37
# Removes orphaned/unused Payment fields:
#   - cf_order_id (duplicate of gateway_order_id)
#   - cf_payment_id (duplicate of gateway_payment_id)
# Payment now uses consistent gateway_* naming

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_move_cf_fields_to_payment'),
    ]

    operations = [
        # Note: cf_order_id and cf_payment_id were dropped via manual SQL
        # This migration documents the cleanup
    ]
