# Generated by Django 4.2 on 2026-04-05 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_clean_orphaned_payment_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='cf_order_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='cf_payment_id',
        ),
    ]
