# Generated by Django 4.2.29 on 2026-04-14 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0003_pcbuild_is_custom_pcbuild_is_prebuilt'),
        ('orders', '0005_orderitem_build_alter_cartitem_build_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='build',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='builds.pcbuild'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='build',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='builds.pcbuild'),
        ),
    ]
