# Generated by Django 4.2 on 2026-04-14 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0003_pcbuild_is_custom_pcbuild_is_prebuilt'),
        ('orders', '0006_alter_cartitem_build_alter_orderitem_build'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='build_source',
            field=models.ForeignKey(blank=True, help_text='If this item came from a prebuilt PC, reference the original build', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_cart_items', to='builds.pcbuild'),
        ),
    ]
