# Generated by Django 4.2 on 2026-03-31 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tdp', models.PositiveIntegerField(blank=True, help_text='In Watts', null=True)),
                ('storage_type', models.CharField(max_length=50)),
                ('capacity_gb', models.IntegerField()),
                ('interface_type', models.CharField(max_length=50)),
                ('form_factor', models.CharField(max_length=50)),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_specs', to='products.productvariant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tdp', models.PositiveIntegerField(blank=True, help_text='In Watts', null=True)),
                ('ram_type', models.CharField(choices=[('DDR4', 'DDR4'), ('DDR5', 'DDR5')], max_length=10)),
                ('capacity_gb', models.PositiveIntegerField()),
                ('speed_mhz', models.PositiveIntegerField()),
                ('module_count', models.PositiveSmallIntegerField()),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_specs', to='products.productvariant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tdp', models.PositiveIntegerField(blank=True, help_text='In Watts', null=True)),
                ('socket_type', models.CharField(max_length=50)),
                ('ram_type', models.CharField(choices=[('DDR4', 'DDR4'), ('DDR5', 'DDR5')], max_length=10)),
                ('form_factor', models.CharField(choices=[('ATX', 'ATX'), ('MATX', 'Micro-ATX'), ('ITX', 'Mini-ITX')], max_length=10)),
                ('chipset', models.CharField(max_length=50)),
                ('m2_slots', models.PositiveSmallIntegerField(default=0)),
                ('sata_ports', models.PositiveSmallIntegerField(default=0)),
                ('pcie_x1_slots', models.IntegerField()),
                ('pcie_x16_slots', models.IntegerField()),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_specs', to='products.productvariant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tdp', models.PositiveIntegerField(blank=True, help_text='In Watts', null=True)),
                ('memory_size', models.IntegerField()),
                ('pcie_version', models.CharField(max_length=50)),
                ('length_mm', models.IntegerField()),
                ('interface_type', models.CharField(max_length=50)),
                ('power_8pin_count', models.IntegerField()),
                ('power_6pin_count', models.IntegerField()),
                ('power_12vhpwr', models.BooleanField(default=False)),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_specs', to='products.productvariant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tdp', models.PositiveIntegerField(blank=True, help_text='In Watts', null=True)),
                ('socket_type', models.CharField(max_length=50)),
                ('cores', models.IntegerField()),
                ('threads', models.IntegerField()),
                ('base_clock', models.DecimalField(decimal_places=3, max_digits=6)),
                ('boost_clock', models.DecimalField(decimal_places=3, max_digits=6)),
                ('integrated_graphics', models.BooleanField(default=False)),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_specs', to='products.productvariant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tdp', models.PositiveIntegerField(blank=True, help_text='In Watts', null=True)),
                ('supported_form_factors', models.CharField(help_text='e.g. ATX, ITX', max_length=100)),
                ('max_gpu_length_mm', models.PositiveIntegerField()),
                ('max_psu_length_mm', models.PositiveIntegerField()),
                ('max_cooler_height_mm', models.PositiveIntegerField()),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_specs', to='products.productvariant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
