# Generated by Django 4.2 on 2026-03-31 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_storage_ram_motherboard_gpu_cpu_cabinet'),
    ]

    operations = [
        migrations.CreateModel(
            name='PSU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tdp', models.PositiveIntegerField(blank=True, help_text='In Watts', null=True)),
                ('wattage', models.PositiveIntegerField(help_text='In Watts')),
                ('form_factor', models.CharField(choices=[('ATX', 'ATX'), ('MATX', 'Micro-ATX'), ('ITX', 'Mini-ITX')], max_length=10)),
                ('efficiency_rating', models.CharField(choices=[('80+', '80 Plus'), ('BRONZE', '80+ Bronze'), ('SILVER', '80+ Silver'), ('GOLD', '80+ Gold'), ('PLATINUM', '80+ Platinum'), ('TITANIUM', '80+ Titanium')], max_length=15)),
                ('modularity', models.CharField(choices=[('NON', 'Non-Modular'), ('SEMI', 'Semi-Modular'), ('FULL', 'Fully-Modular')], default='NON', max_length=10)),
                ('length_mm', models.PositiveIntegerField()),
                ('power_8pin_count', models.PositiveSmallIntegerField(default=0, help_text='CPU/PCIe 8-pin')),
                ('power_6pin_count', models.PositiveSmallIntegerField(default=0, help_text='PCIe 6-pin')),
                ('power_12vhpwr', models.BooleanField(default=False, help_text='16-pin connector for modern GPUs')),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_specs', to='products.productvariant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
