# Generated by Django 4.2.29 on 2026-04-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_cooler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooler',
            name='cooler_type',
            field=models.CharField(choices=[('AIR', 'Air Cooler'), ('AIO', 'AIO Liquid Cooler')], help_text='AIR = tower fan cooler  |  AIO = all-in-one liquid cooler', max_length=10),
        ),
        migrations.AlterField(
            model_name='cooler',
            name='height_mm',
            field=models.PositiveIntegerField(help_text='Tower height in mm — checked against case max_cooler_height_mm. Set to 0 for AIO coolers where tower height is not applicable.'),
        ),
        migrations.AlterField(
            model_name='cooler',
            name='radiator_size_mm',
            field=models.PositiveIntegerField(blank=True, help_text='Radiator length in mm (120, 240, 280, 360 …). Leave blank for air coolers.', null=True),
        ),
        migrations.AlterField(
            model_name='cooler',
            name='supported_sockets',
            field=models.JSONField(default=list, help_text='Compatible CPU sockets, e.g. ["AM5", "LGA1700"]'),
        ),
    ]
